FROM oven/bun:latest

WORKDIR /app

COPY package.json bun.lock tsconfig.base.json ./

RUN bun install --development

COPY . .

# Build library buildable
RUN bunx nx build utils
RUN bunx nx build ui

# Build aplikasi
RUN bunx nx build toko

# Setup symlink alias path
RUN mkdir -p node_modules/@tainext && \
    cd node_modules/@tainext && \
    ln -s ../../dist/libs/ui ui && \
    ln -s ../../dist/libs/utils utils

# Jalankan server
CMD ["bun", "run", "next", "start", "-p", "3000"]